//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursipovisheniakvalificaciy.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruppy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruppy()
        {
            this.Nagruzka = new HashSet<Nagruzka>();
        }
    
        public int Nomer_gruppy { get; set; }
        public string Specialnost { get; set; }
        public string Otdelenie { get; set; }
        public int Kolichestvo_studentov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nagruzka> Nagruzka { get; set; }
    }
}
