//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursipovisheniakvalificaciy.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagruzka
    {
        public int Kod_prepodavatelya { get; set; }
        public int Nomer_gruppy { get; set; }
        public int Kolichestvo_chasov { get; set; }
        public string Predmet { get; set; }
        public string Tip_zanyatiya { get; set; }
        public decimal Oplata { get; set; }
    
        public virtual Gruppy Gruppy { get; set; }
        public virtual Prepodavateli Prepodavateli { get; set; }
    }
}
